### ISSUE TITLE
Proposal with editor actions 

### ISSUE THREAD

**Issue by ghost** [LiveEmily/nextpad#3]
Hi;

I think it would be a good idea to make the Ctrl+Q (Quit) and Ctrl+S (Save) actions available inside and outside of insert mode

**Comment by LiveEmily** [comment]
Realised this logic wasn't implented well, will add this quick fix tomorrow.
ToDo for self: correct the switch case shortcuts.

**Comment by LiveEmily** [comment]
Added in commit: 6bfff44e7ad18255662b66bd0480c7c38e2ec376.
Closing this issue now since it should be good.
